# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-11-arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Enable Long Paths
        shell: powershell
        run: |
           New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem" -Name "LongPathsEnabled" -Value 1 -PropertyType DWORD -Force
      - name: Test Long Paths
        shell: cmd
        run: |
           mkdir  bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
           cd     bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
           mkdir  qr243vbiqr243vbiqr243vbiqr243vbiqr243vbi
           cd     qr243vbiqr243vbiqr243vbiqr243vbiqr243vbi
           mkdir  llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
           cd     llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll
           copy NUL aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: vcpkg build
        uses: johnwason/vcpkg-action@v7
        id: vcpkg
        with:
          pkgs: qtgrpc qtcharts qtdeclarative qtbase qttools
          triplet: arm64-windows
          token: ${{ github.token }}

      - name: Upload vcpkg cache as artifact
        uses: actions/upload-artifact@v5
        with:
          name: my-artifact  # Name of the artifact
          path: ./vcpkg
